version: 2
services:
  - type: web
    name: international-tijarat-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb://localhost:27017/tijarat
  - type: static
    name: international-tijarat-frontend
    staticPublishPath: ./frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
